export const AUTH_ACTIONS = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",

  REGISTER_REQUEST: "REGISTER_REQUEST",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAILURE: "REGISTER_FAILURE",

  LOGOUT_REQUEST:"LOGOUT_REQUEST",
  LOGOUT: "LOGOUT",

  REFRESH_TOKEN_SUCCESS: "REFRESH_TOKEN_SUCCESS",
};


export const WORKSPACE_ACTIONS = {
  WORKSPACE_REQUEST: "WORKSPACE_REQUEST",
  SET_WORKSPACES: "SET_WORKSPACES",
  ADD_WORKSPACE: "ADD_WORKSPACE",
  EDIT_WORKSPACE: "EDIT_WORKSPACE",
  DELETE_WORKSPACE: "DELETE_WORKSPACE",
  SET_ACTIVE_WORKSPACE: "SET_ACTIVE_WORKSPACE",
  WORKSPACE_FAILURE: "WORKSPACE_FAILURE",
};


export const PROJECT_ACTIONS = {
  PROJECT_REQUEST: "PROJECT_REQUEST",
  SET_PROJECTS: "SET_PROJECTS",
  SET_CURRENT_PROJECT: "SET_CURRENT_PROJECT",
  ADD_PROJECT: "ADD_PROJECT",
  UPDATE_PROJECT: "UPDATE_PROJECT",
  DELETE_PROJECT: "DELETE_PROJECT",
  PROJECT_ERROR: "PROJECT_ERROR",
};


export const TASK_ACTIONS = {
  TASK_REQUEST: "TASK_REQUEST",
  SET_TASKS: "SET_TASKS",
  ADD_TASK: "ADD_TASK",
  UPDATE_TASK: "UPDATE_TASK",
  DELETE_TASK: "DELETE_TASK",
  USER_TASK_REQUEST:"USER_TASK_REQUEST",
  SET_USER_TASKS: "SET_USER_TASKS",
  TASK_FAILURE: "TASK_FAILURE",
};


export const COMMENT_ACTIONS = {
  COMMENT_REQUEST: "COMMENT_REQUEST",
  SET_COMMENTS: "SET_COMMENTS",
  ADD_COMMENT: "ADD_COMMENT",
  UPDATE_COMMENT: "UPDATE_COMMENT",
  DELETE_COMMENT: "DELETE_COMMENT",
  COMMENT_FAILURE: "COMMENT_FAILURE",
};

export const ANALYTICS_ACTIONS = {
  ANALYTICS_REQUEST: "ANALYTICS_REQUEST",
  SET_PROJECT_ANALYTICS: "SET_PROJECT_ANALYTICS",
  ANALYTICS_FAILURE: "ANALYTICS_FAILURE",
};


export const DASHBOARD_ACTIONS = {
  DASHBOARD_REQUEST: "DASHBOARD_REQUEST",
  SET_DASHBOARD_DATA: "SET_DASHBOARD_DATA",
  DASHBOARD_FAILURE: "DASHBOARD_FAILURE",
};